export const ICEBREAKERS = [
  "Parece que el destino nos ha sentado en la misma boda... algo tendrá que ver con esto 💫",
  "De todas las bodas del mundo, tuviste que aparecer en la mía (bueno, en la de Nacho y Rocío) 🥂",
  "El algoritmo del amor de Nacho y Rocío ha hablado: ¡somos compatibles! 💘",
  "Match en la boda más bonita del año... esto ya empieza bien 🌸",
  "Dicen que en las bodas pasan cosas mágicas. Creo que acaban de tener razón ✨",
  "¿Coincidencia o destino? La lista de invitados tenía un plan secreto 🎩",
  "Bienvenid@ a mi DM de boda. Aquí se habla de amor, croquetas y pista de baile 💃",
  "Nacho y Rocío se casaron y de paso nos presentaron. Les debemos una 🍾",
  "Si la boda ya es perfecta, imagínate lo que puede pasar después 😏",
  "Match conseguido. Siguiente paso: bailar juntos en la pista sin pisarnos 🕺",
  "De invitado a invitada hay un paso... y ese paso lo acaba de dar el amor ❤️",
  "¿Te apuntas a ser mi compañer@ de mesa y de aventuras? La boda es el principio 🌹",
  "El photocall puede esperar, primero dime: ¿eres de equipo croqueta o equipo jamón? 🍖",
  "Nacho y Rocío llevan años construyendo su historia. Nosotros llevamos... segundos. Buen comienzo 😊",
  "Alerta de match en boda de lujo. Repito: alerta de match en boda de lujo 🚨",
  "¿Primera vez que te ponen en contacto vía mini-Tinder en una boda? A mí también 😂",
  "Si esto fuera una peli romántica, esta sería la escena del primer mensaje 🎬",
  "Match de boda: más exclusivo que la lista de invitados VIP 🌟",
  "Hola. Soy la persona con la que vas a tener una conversación muy interesante esta noche 👋",
  "No sé tú, pero yo ya estoy pensando en qué canción pediremos al DJ 🎵",
  "Dos desconocidos, una boda, un match... los ingredientes de una buena historia 📖",
  "¿Crees en el amor a primera vista o tengo que pasarte otra vez por delante? 😄",
  "La novia lleva el ramo, el novio el anillo... y nosotros llevamos este match 💍",
  "Sede oficial del flechazo: boda de Nacho y Rocío, junio de 2026 🎊",
  "Si al final bailamos juntos, Nacho y Rocío se llevan todo el mérito 🕊️",
];
